version: '3.8'

services:
  # apache:
  #   image: httpd:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./tu_web:/usr/local/apache2/htdocs
  #   restart: always

  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile.nodejs
    volumes:
      - ./:/app
    command: node index.js
    restart: always
