FROM node:latest

# Instala Python y pip
RUN apt-get update && apt-get install -y \
    python3

RUN apt install python3-pip

WORKDIR /app

# Copia los archivos de paquete de Node.js
COPY package*.json ./

# Instala las dependencias de Node.js
RUN npm install

# Copia los archivos de la aplicación Node.js
COPY . .

# Instala matplotlib de Python 3
RUN pip3 install matplotlib

# Expone el puerto 3000
EXPOSE 3000

# Ejecuta el servidor de Node.js
CMD ["node", "index.js"]
