version: '3'

services:
  

  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "3169:3169"
    volumes:
      - ./:/app
    command: node index.js
    restart: always
